" Set syntax
syntax on

" indent stuff
set autoindent
set copyindent
set smartindent
set smarttab
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

"set cursorcolumn
set autochdir
set cursorline
set equalalways
set ruler

"set foldlevel=0
set nofoldenable
set foldmethod=syntax

set undolevels=1000
set history=1000
set laststatus=2
set timeoutlen=100

set modelines=0
set nocompatible
set noexpandtab

set showmatch
set showcmd
set splitright
set scrolloff=5

set title

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
  "filetype plugin indent on
endif

set statusline=%F%=%l,%v%20p%%

map <C-n> <C-w>h
map <C-m> <C-w>l
map <C-k> <C-w>k
map <C-j> <C-w>j

map <C-l> :tabnext<CR>
map <C-h> :tabprevious<CR>
imap <C-l> <C-c>:tabnext<CR>
imap <C-h> <C-c>:tabprevious<CR>

map <C-t> :tabnew
imap <C-t> <C-c>:tabnew<CR>

" Quick write session with F2, restore with F3
map <F2> :mksession! ~/vim_session <cr>
map <F3> :source ~/vim_session <cr>
map <F4> :NERDTreeToggle<cr>

map		<f8> :w<cr>
imap	<f8> <C-c>:w<cr>

map		<F9> zm
map		<F10> zO

"
map :W :w

let php_sql_query		= 1
let php_htmlInStrings	= 1
let php_folding			= 1

let NERDTreeQuitOnOpen	= 1

au BufRead,BufNewFile jquery.*.js	set ft=javascript syntax=jquery
au BufRead,BufNewFile *.js			set ft=javascript syntax=jquery
au BufRead,BufNewFile *.twig		set ft=htmljinja

"colorscheme molokai
colorscheme torte
